### ISSUE TITLE
consult the cross-encoder for reranking

### ISSUE THREAD

**Issue by GNEHUY** [Hannibal046/nanoColBERT#6]
Could you kindly recommend or guide a simple implementation of BERT for reranking? For instance, something akin to Figure c, involving all-to-all interaction or a cross-encoder approach.
![ColBERT](https://github.com/Hannibal046/nanoColBERT/assets/93430230/f10c35c2-3cbd-4642-8fd8-2cef6c3a9c3f)
I am aware of the implementation available at https://github.com/nyu-dl/dl4marco-bert, but I am finding it a bit complex and this repository does not utilize the PyTorch architecture but instead employs the TensorFlow framework. Thank you for your help.

**Comment by Hannibal046** [comment]
Hi, I am not aware of any code repo dedicated to BERT Reranking. But I do know a few repos containing reranking as one of their baselines, such as:
- [RocketQA](https://github.com/PaddlePaddle/RocketQA/blob/main/rocketqa/encoder/cross_encoder.py)
- [ColBERT](https://github.com/stanford-futuredata/ColBERT/tree/main/colbert/modeling/reranker)
- [fairseq](https://github.com/facebookresearch/fairseq/tree/main/examples/discriminative_reranking_nmt)

They are all based on PyTorch (although deeply integrated into the corresponding library)

**Comment by GNEHUY** [comment]
Thank you for your prompt response. These libraries indeed have some baselines, but they are deeply integrated into certain libraries, making it difficult to understand. I know that the first time BERT was used for ranking tasks was in this paper https://arxiv.org/abs/1901.04085, and its library is https://github.com/nyu-dl/dl4marco-bert, later also known as monoBERT. I couldn't find an easily understandable implementation of monoBERT on GitHub. I'm not sure if you are familiar with this content or interested in providing some guidance and a simple implementation method.

**Comment by Hannibal046** [comment]
Hello,

Apologies, but I have no immediate plans to recreate this model. If you're keen, you might consider giving it a go yourself—it could certainly be an enjoyable project!

**Comment by GNEHUY** [comment]
Thank you for your response! I appreciate the suggestion and encouragement to work on recreating the model myself.  Thanks again for your time and advice!

**Comment by NLPJCL** [comment]
I have implemented one：RAG-Retrieval, but currently I have only tested it in Chinese, English should be fine too。and there are only tutorials written in Chinese. The English version will be added later.
https://github.com/NLPJCL/RAG-Retrieval/tree/master/rag-retrieval/reranker
@GNEHUY

**Comment by NLPJCL** [comment]
@Hannibal046  ColBert referred to your implementation and it has been cited in the Zhihu article. Thank you!

**Comment by Hannibal046** [comment]
Happy to know!
